services:
  decentragri-ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: decentragri-ai-agent
    container_name: decentragri-ai-agent
    restart: unless-stopped
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - decentragri-network

  decentragri-memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: decentragri-memgraph
    restart: unless-stopped
    ports:
      - "7449:7444"
      - "7689:7687"
    environment:
      - MEMGRAPH_USER=decentragri
      - MEMGRAPH_PASSWORD=UXxTPCxxOpC7Y2JcFgsrgfs5635irhmmwqXwedwdddadaYw5StjbwK32323h0pdy/DadfdfB9gQZDgVbePoXJgLA==
    networks:
      - decentragri-network

  decentragri-engine:
    image: thirdweb/engine:latest
    container_name: decentragri-engine
    environment:
      - ENCRYPTION_PASSWORD=${ENGINE_ENCRYPTION_PASSWORD}
      - THIRDWEB_API_SECRET_KEY=${SECRET_KEY}
      - ADMIN_WALLET_ADDRESS=${ENGINE_ADMIN_WALLET_ADDRESS}
      - POSTGRES_CONNECTION_URL=postgresql://postgres:${POSTGRES_PASSWORD}@decentragri-postgres:5432/postgres?sslmode=disable
      - REDIS_URL=redis://decentragri-valkey:6379/0
      - ENABLE_HTTPS=false
      - TRUST_PROXY=true
    ports:
      - "127.0.0.1:3006:3005"
    cpus: "1"
    restart: always
    networks:
      - decentragri-network

  decentragri-valkey:
    image: valkey/valkey:latest
    container_name: decentragri-valkey
    ports:
      - "127.0.0.1:6388:6379"
    networks:
      - decentragri-network
    volumes:
      - valkey-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 2s

  decentragri-postgres:
    image: postgres
    container_name: decentragri-postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: postgres -c 'max_connections=250'
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - decentragri-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 10s

  decentragri-seaweed-master:
    image: chrislusf/seaweedfs:latest
    container_name: decentragri-seaweed-master
    command: "master -ip=decentragri-seaweed-master -mdir=/data"
    ports:
      - "9333:9333"  # UI/API for master
    volumes:
      - seaweed-master-data:/data
    networks:
      - decentragri-network

  decentragri-seaweed-volume:
    image: chrislusf/seaweedfs:latest
    container_name: decentragri-seaweed-volume
    command: "volume -max=5 -mserver=decentragri-seaweed-master:9333 -ip=decentragri-seaweed-volume -dir=/data"
    ports:
      - "8086:8080"  # admin UI port remapped to 8086 on host
      - "8087:8081"  # volume public port remapped to 8087 on host
    volumes:
      - seaweed-volume-data:/data
    depends_on:
      - decentragri-seaweed-master
    networks:
      - decentragri-network

  decentragri-seaweed-filer:
    image: chrislusf/seaweedfs:latest
    container_name: decentragri-seaweed-filer
    command: "filer -master=decentragri-seaweed-master:9333"
    ports:
      - "8888:8888"  # Filer UI/API
      - "8333:8333"  # Optional S3 API
    volumes:
      - seaweed-filer-data:/data
    depends_on:
      - decentragri-seaweed-master
    networks:
      - decentragri-network


volumes:
  valkey-data:
  postgres-data:
  seaweed-master-data:
  seaweed-volume-data:
  seaweed-filer-data:

networks:
  decentragri-network:
    driver: bridge
